name: Test Applications
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Test-Application:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Tests for Applications"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true
      - run: npm install
      - run: npm run test
      - run: npm run lint
